---
- name: Patch example
  hosts: all

  tasks:
    - name: Ensure tmp ansible dir
      ansible.builtin.file:
        path: /tmp/ansible
        state: directory
        mode: 777

    - name: Copy ansible dir
      rsync:
        src: "{{ playbook_dir }}/"
        dest: /tmp/ansible/
        recursive: yes
        delete: yes

    - name: Get the dist info
      shell: "uname -a"
      register: distinfo

    - name: Display the dist info
      debug: msg="{{ distinfo.stdout }}"
    
    - name: Some other op
      shell: "ls -la"
      args:
        chdir: /tmp/ansible
