apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: patch-device-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.12, pipelines.kubeflow.org/pipeline_compilation_time: '2022-08-31T12:22:05.771018',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A Kubeflow pipeline running
      Ansible playbook from a git repo on a subset of devices", "inputs": [{"name":
      "playbook_repo"}, {"name": "playbook_path"}, {"name": "ansible_limit"}], "name":
      "Patch device"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.12}
spec:
  entrypoint: patch-device
  templates:
  - name: patch-device
    inputs:
      parameters:
      - {name: ansible_limit}
      - {name: playbook_path}
      - {name: playbook_repo}
    dag:
      tasks:
      - name: run-ansible-playbook
        template: run-ansible-playbook
        arguments:
          parameters:
          - {name: ansible_limit, value: '{{inputs.parameters.ansible_limit}}'}
          - {name: playbook_path, value: '{{inputs.parameters.playbook_path}}'}
          - {name: playbook_repo, value: '{{inputs.parameters.playbook_repo}}'}
  - name: run-ansible-playbook
    container:
      args:
      - |2

        set -eo pipefail
        export CLUSTER=$(if [ "${PROJECT_ID}" == "teknoir" ]; then echo "teknoir-cluster"; else echo "teknoir-dev-cluster"; fi)
        echo "Get credentials to ${CLUSTER} GKE cluster"
        gcloud container clusters get-credentials ${CLUSTER} --zone us-central1-c --project ${PROJECT_ID}
        git clone https://github.com/teknoir/device-patch-base.git ./workdir
        cd workdir
        ls
        chmod +x run_playbook.sh
        echo "./run_playbook.sh --repo ${REPO} --playbook ${PLAYBOOK} --limit "${LIMIT}""
        ./run_playbook.sh --repo ${REPO} --playbook ${PLAYBOOK} --limit "'${LIMIT}'"
      command: [bash, -c]
      env:
      - {name: NAMESPACE, value: teknoir-ai}
      - {name: PROJECT_ID, value: teknoir}
      - {name: REPO, value: '{{inputs.parameters.playbook_repo}}'}
      - {name: PLAYBOOK, value: '{{inputs.parameters.playbook_path}}'}
      - {name: LIMIT, value: '{{inputs.parameters.ansible_limit}}'}
      image: gcr.io/teknoir/edgebuild
    inputs:
      parameters:
      - {name: ansible_limit}
      - {name: playbook_path}
      - {name: playbook_repo}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.12
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/max_cache_staleness: P0D}
  arguments:
    parameters:
    - {name: playbook_repo}
    - {name: playbook_path}
    - {name: ansible_limit}
  serviceAccountName: pipeline-runner
